version: "3"
services:
  app:
    container_name: {{ cookiecutter.project_slug }}-app
    build:
      context: .
    environment:
      - PHP_ENV=${PHP_ENV}
    volumes:
      - .:/app

  http:
    container_name: {{ cookiecutter.project_slug }}-http
    image: nginx:alpine
    ports:
      - "{{ cookiecutter.docker_port }}:80"
    volumes:
      - .:/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - app
